name: Build Unity APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Unity packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/unity
          key: ${{ runner.os }}-unity

      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 2022.3.4f1

      - name: Build Android APK
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
          unityVersion: 2022.3.4f1
          projectPath: .
          buildsPath: build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/**/*.apk
